"""add upgrade table

Revision ID: 121a12d5571c
Revises: ca932a9dfc9b
Create Date: 2023-02-05 20:14:18.918205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121a12d5571c'
down_revision = 'ca932a9dfc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_match', sa.String(
            length=100), nullable=True, default='N/A'))

    with op.batch_alter_table('mes_grid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_match', sa.String(
            length=100), nullable=True, default='N/A'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mes_grid', schema=None) as batch_op:
        batch_op.drop_column('numero_match')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('numero_match')

    # ### end Alembic commands ###
