"""add grid

Revision ID: ca932a9dfc9b
Revises: e1333d0822ad
Create Date: 2023-02-05 19:49:17.047200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca932a9dfc9b'
down_revision = 'e1333d0822ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mes_grid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('categorie_match', sa.String(length=100), nullable=False),
    sa.Column('equipe1', sa.String(length=100), nullable=False),
    sa.Column('equipe2', sa.String(length=100), nullable=False),
    sa.Column('resultat', sa.String(length=100), nullable=False),
    sa.Column('etat', sa.String(length=100), nullable=False),
    sa.Column('date_fin', sa.String(length=100), nullable=False),
    sa.Column('correct_resultat', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mes_grid')
    # ### end Alembic commands ###
