"""add table match

Revision ID: e1333d0822ad
Revises: 0c7601bf8325
Create Date: 2023-02-04 00:14:30.041707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1333d0822ad'
down_revision = '0c7601bf8325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('categorie_match', sa.String(length=100), nullable=False),
    sa.Column('equipe1', sa.String(length=100), nullable=False),
    sa.Column('equipe2', sa.String(length=100), nullable=False),
    sa.Column('resultat', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
