"""update table mes grid

Revision ID: f043c992f948
Revises: 4814e9fd9034
Create Date: 2023-02-11 19:52:14.770051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f043c992f948'
down_revision = '4814e9fd9034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mes_grid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_grid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mes_grid', schema=None) as batch_op:
        batch_op.drop_column('numero_grid')

    # ### end Alembic commands ###
